### ISSUE TITLE
internodes, incorrect comment

### ISSUE THREAD

**Issue by MiYanni** [jankovicsandras/imagetracerjava#4]
In internodes, the value 4.0 should be West and not North.
![image](https://cloud.githubusercontent.com/assets/17788297/18453728/821c1e9c-78f5-11e6-872b-e5ab2280f7b7.png)

**Comment by jankovicsandras** [comment]
You're right, the comment is wrong, it should be `{ thispoint[2] = 4.0; }// W`. But the actual code is OK.

```
        6 N
   5 NW |  7 NE
      \ | / 
4 W --  8  -- 0 East
      / | \
   3 SW |  1 SE
        2 S

```
