### ISSUE TITLE
Convert to White/Black

### ISSUE THREAD

**Issue by egemenozkan** [jankovicsandras/imagetracerjava#5]
Hello,
How can we change image color black and background color white ? Which options should be changed ?

**Comment by jankovicsandras** [comment]
Hi,

There was a bug in ```generatepalette()``` which caused wrong grayscale palettes, but this is [fixed now](https://github.com/jankovicsandras/imagetracerjava/commit/2e8da38d67ed6268a037f67d154a10b6482161db#diff-62e7b454584a60d8628afedc9a0bd12bR374). ☺

Posterizing example from the command line:
```bash
java -jar ImageTracer.jar panda.png outfilename panda_posterized.svg colorsampling 0 numberofcolors 2 mincolorratio 0 colorquantcycles 1
```

or in Java:

```java
import jankovicsandras.imagetracer.ImageTracer;

...

// Options
HashMap<String,Float> options = new HashMap<String,Float>();

// Color quantization
options.put("colorsampling",0f); // 1f means true ; 0f means false: starting with generated palette
options.put("numberofcolors",2f);
options.put("mincolorratio",0f);
options.put("colorquantcycles",1f);

ImageTracer.saveString(
				"output.svg" ,
				ImageTracer.imageToSVG("input.jpg",options,null)
);
```

You can also use a custom palette with these color quantization options, I recommend reading the example on the front page and this:
https://github.com/jankovicsandras/imagetracerjava/blob/master/deterministic.md
