### ISSUE TITLE
Consultation on conversion of bitmap images to lines SVG

### ISSUE THREAD

**Issue by asegurpe** [jankovicsandras/imagetracerjava#7]
Hi András,

I'm Alejandro, the same that contact you in your repository imagetracerjs. About the issue I asked you, also I need do it in the java backend, this is possible using your project imagetracejava?

Again thanks so much.
Alejandro

**Comment by jankovicsandras** [comment]
Hi Alejandro,

Yes, it's possible in theory. I've implemented the "shape peeling" I recommended in [that Issue](https://github.com/jankovicsandras/imagetracerjs/issues/23) and it works, so I guess a similar one would work in Java. Sadly, I don't have time to develop this for free, as it's not in the scope of this project. If you're interested in payed consulting, please send me an email to andras@jankovics.net .
